// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sarah.Monitoring.WebApi.Data;

#nullable disable

namespace Sarah.Monitoring.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260118103953_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.AlarmScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AlarmTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasRecurrence")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNichtInFerien")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNurInFerien")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurrence")
                        .HasColumnType("boolean");

                    b.Property<int>("RecurrenceDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("RecurrenceIsEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("RecurrenceTime")
                        .HasColumnType("interval");

                    b.Property<string>("SerializedRecurrence")
                        .HasColumnType("text");

                    b.Property<string>("TargetSpeaker")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlarmSchedules", (string)null);
                });

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.DeseaseKpiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeseaseName")
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<double>("FieldValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("DeseaseKpis", (string)null);
                });

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.DeviceInfoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("Id_Room")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReadonly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte>("NodeID")
                        .HasColumnType("smallint");

                    b.Property<int>("SpecificType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.DeviceTraceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<byte>("NodeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Property")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeviceTraces", (string)null);
                });

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.MonitoringDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MonitoringDatas", (string)null);
                });

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.PersonInfoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("GPSTrackerID")
                        .HasColumnType("smallint");

                    b.Property<string>("MobilePhoneHostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.RoomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Sarah.Monitoring.WebApi.Data.Entities.TemperatureScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<long?>("Id_Room")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TargetTemperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TemperatureSchedules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
