/**
 * Sarah Room Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetailsModel } from '../model/models';
import { RoomDtoModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoomsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiRoomsGet(extraHttpRequestParams?: any): Observable<Array<RoomDtoModel>>;

    /**
     * 
     * 
     * @param id 
     */
    apiRoomsIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param isFavourite 
     */
    apiRoomsIdFavouriteIsFavouritePut(id: number, isFavourite: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiRoomsIdGet(id: number, extraHttpRequestParams?: any): Observable<RoomDtoModel>;

    /**
     * 
     * 
     * @param id 
     * @param roomDtoModel 
     */
    apiRoomsIdPut(id: number, roomDtoModel?: RoomDtoModel, extraHttpRequestParams?: any): Observable<RoomDtoModel>;

    /**
     * 
     * 
     * @param roomDtoModel 
     */
    apiRoomsPost(roomDtoModel?: RoomDtoModel, extraHttpRequestParams?: any): Observable<RoomDtoModel>;

}
