/**
 * Sarah Persons Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SensorDataModel } from './sensorData';
import { LocatorPositionModel } from './locatorPosition';


export interface IGPSTrackerModel { 
    readonly nodeID?: number;
    readonly stateInfo?: string | null;
    readonly classDescription?: string | null;
    readonly isActive?: boolean | null;
    battery?: SensorDataModel;
    position?: LocatorPositionModel;
    readonly positionTrace?: Array<LocatorPositionModel> | null;
    readonly lastMessageReceived?: string;
    isButtonPressed?: SensorDataModel;
}

