/**
 * Sarah Persons Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SensorDataModel } from './sensorData';


export interface LocatorPositionModel { 
    longtitude?: SensorDataModel;
    latitude?: SensorDataModel;
    readonly measureTime?: string;
    readonly isValid?: boolean;
}

