/**
 * Sarah Persons Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IGPSTrackerModel } from './iGPSTracker';
import { IGeoFenceModel } from './iGeoFence';


export interface PersonDtoModel { 
    id?: number;
    name?: string | null;
    mobilePhoneHostname?: string | null;
    gpsTrackerID?: number;
    isAtHome?: boolean;
    trackerDeviceName?: string | null;
    gpsTracker?: IGPSTrackerModel;
    currentGeoFence?: IGeoFenceModel;
}

