/**
 * Sarah Persons Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonResponseDtoModel { 
    id?: number;
    name?: string | null;
    gpsTrackerID?: number;
    gpsTrackerName?: string | null;
    currentGeoFence?: string | null;
    currentPosition?: string | null;
    isAtHome?: boolean;
    mobilePhoneHostname?: string | null;
    isFavourite?: boolean;
}

