/**
 * Sarah Persons Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SensorDataModel { 
    value?: number;
    unit?: string | null;
    timestamp?: string;
}

