/**
 * Sarah Rules Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlarmScheduleEntityModel } from '../model/models';
import { KernelChatMessageRequestDtoModel } from '../model/models';
import { KernelChatMessageResponseDtoModel } from '../model/models';
import { KernelConversationMessageDtoModel } from '../model/models';
import { PromptRuleDtoModel } from '../model/models';
import { PromptRuleUpsertDtoModel } from '../model/models';
import { RuleExecutionLogDtoModel } from '../model/models';
import { RuleOverviewDtoModel } from '../model/models';
import { TemperatureScheduleEntityModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RulesClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiRulesAlarmsActiveGet(extraHttpRequestParams?: any): Observable<Array<AlarmScheduleEntityModel>>;

    /**
     * 
     * 
     */
    apiRulesAlarmsGet(extraHttpRequestParams?: any): Observable<Array<AlarmScheduleEntityModel>>;

    /**
     * 
     * 
     * @param id 
     */
    apiRulesAlarmsIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiRulesAlarmsIdGet(id: number, extraHttpRequestParams?: any): Observable<AlarmScheduleEntityModel>;

    /**
     * 
     * 
     * @param id 
     * @param alarmScheduleEntityModel 
     */
    apiRulesAlarmsIdPut(id: number, alarmScheduleEntityModel?: AlarmScheduleEntityModel, extraHttpRequestParams?: any): Observable<AlarmScheduleEntityModel>;

    /**
     * 
     * 
     * @param id 
     */
    apiRulesAlarmsIdTogglePatch(id: number, extraHttpRequestParams?: any): Observable<AlarmScheduleEntityModel>;

    /**
     * 
     * 
     * @param alarmScheduleEntityModel 
     */
    apiRulesAlarmsPost(alarmScheduleEntityModel?: AlarmScheduleEntityModel, extraHttpRequestParams?: any): Observable<AlarmScheduleEntityModel>;

    /**
     * 
     * 
     */
    apiRulesGet(extraHttpRequestParams?: any): Observable<Array<RuleOverviewDtoModel>>;

    /**
     * 
     * 
     */
    apiRulesKernelConversationDelete(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param conversationId 
     * @param hours 
     * @param limit 
     */
    apiRulesKernelConversationGet(conversationId?: string, hours?: number, limit?: number, extraHttpRequestParams?: any): Observable<Array<KernelConversationMessageDtoModel>>;

    /**
     * 
     * 
     * @param kernelChatMessageRequestDtoModel 
     */
    apiRulesKernelConversationMessagePost(kernelChatMessageRequestDtoModel?: KernelChatMessageRequestDtoModel, extraHttpRequestParams?: any): Observable<KernelChatMessageResponseDtoModel>;

    /**
     * 
     * 
     * @param limit 
     */
    apiRulesLogGet(limit?: number, extraHttpRequestParams?: any): Observable<Array<RuleExecutionLogDtoModel>>;

    /**
     * 
     * 
     */
    apiRulesPromptRulesGet(extraHttpRequestParams?: any): Observable<Array<PromptRuleDtoModel>>;

    /**
     * 
     * 
     * @param id 
     */
    apiRulesPromptRulesIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiRulesPromptRulesIdGet(id: number, extraHttpRequestParams?: any): Observable<PromptRuleDtoModel>;

    /**
     * 
     * 
     * @param id 
     * @param promptRuleUpsertDtoModel 
     */
    apiRulesPromptRulesIdPut(id: number, promptRuleUpsertDtoModel?: PromptRuleUpsertDtoModel, extraHttpRequestParams?: any): Observable<PromptRuleDtoModel>;

    /**
     * 
     * 
     * @param promptRuleUpsertDtoModel 
     */
    apiRulesPromptRulesPost(promptRuleUpsertDtoModel?: PromptRuleUpsertDtoModel, extraHttpRequestParams?: any): Observable<PromptRuleDtoModel>;

    /**
     * 
     * 
     */
    apiRulesStatusGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiRulesTemperaturesGet(extraHttpRequestParams?: any): Observable<Array<TemperatureScheduleEntityModel>>;

    /**
     * 
     * 
     * @param id 
     */
    apiRulesTemperaturesIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiRulesTemperaturesIdGet(id: number, extraHttpRequestParams?: any): Observable<TemperatureScheduleEntityModel>;

    /**
     * 
     * 
     * @param id 
     * @param temperatureScheduleEntityModel 
     */
    apiRulesTemperaturesIdPut(id: number, temperatureScheduleEntityModel?: TemperatureScheduleEntityModel, extraHttpRequestParams?: any): Observable<TemperatureScheduleEntityModel>;

    /**
     * 
     * 
     * @param temperatureScheduleEntityModel 
     */
    apiRulesTemperaturesPost(temperatureScheduleEntityModel?: TemperatureScheduleEntityModel, extraHttpRequestParams?: any): Observable<TemperatureScheduleEntityModel>;

    /**
     * 
     * 
     * @param roomId 
     */
    apiRulesTemperaturesRoomRoomIdGet(roomId: number, extraHttpRequestParams?: any): Observable<Array<TemperatureScheduleEntityModel>>;

    /**
     * 
     * 
     * @param roomId 
     */
    apiRulesTemperaturesRoomRoomIdNextGet(roomId: number, extraHttpRequestParams?: any): Observable<TemperatureScheduleEntityModel>;

}
