/**
 * Sarah Room Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoomDtoModel { 
    id?: number;
    name?: string | null;
    description?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
    isFavourite?: boolean;
}

