# Base image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER app
WORKDIR /app
#server port
EXPOSE 7165

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY . .
RUN rm -f InteLuk.db
WORKDIR "/src/Sarah.Server"
RUN rm -f InteLuk.db
#RUN dotnet build "./Sarah.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish the application
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Sarah.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false



# Final stage
FROM publish AS final

# Start the application
WORKDIR /app
COPY --from=publish /app/publish .
#COPY --from=publish /src/sarah.client/dist/sarah.client ./sarah.client



# Set up Backend and run
WORKDIR /app
ENTRYPOINT ["dotnet", "Sarah.Server.dll"]
