# Stage 1: Build the Angular app
FROM node:20 AS build
WORKDIR /app
COPY ./sarah.client/ ./
RUN npm install
RUN npm run build --prod

# Stage 2: Serve the Angular app
FROM nginx:alpine as final
COPY --from=build /app/dist/sarah.client/browser /usr/share/nginx/html
EXPOSE 4200


# Update Nginx configuration to listen on port 4200, use HTTPS, and log to Docker console
RUN sed -i 's/listen       80;/listen       4200 ssl;/g' /etc/nginx/conf.d/default.conf && \
    echo 'ssl_certificate /etc/ssl/certs/certificate.crt;' >> /etc/nginx/conf.d/default.conf && \
    echo 'ssl_certificate_key /etc/ssl/certs/private.key;' >> /etc/nginx/conf.d/default.conf && \
    sed -i '/http {/a \\n    access_log /dev/stdout;\n    error_log /dev/stderr debug;' /etc/nginx/nginx.conf && \
    sed -i '/location \/ {/a \\n    try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]