# Base image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER app
WORKDIR /app
#server port
EXPOSE 7165
#client port
EXPOSE 4200 

# Install Node.js
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS with-node
RUN apt-get update
RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash
RUN apt-get -y install nodejs
RUN npm install -g @angular/cli

# Copy and build the application
FROM with-node AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY . .
RUN rm -f InteLuk.db
WORKDIR "/src/Sarah.Server"
RUN rm -f InteLuk.db
#RUN dotnet build "./Sarah.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish the application
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Sarah.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false



# Final stage
FROM with-node AS final

# Start the application
WORKDIR /app
COPY --from=publish /app/publish ./sarah.server
COPY --from=publish /src/sarah.client/dist/sarah.client ./sarah.client



# Set up SPA
WORKDIR /app/sarah.server
ENTRYPOINT ["dotnet", "Sarah.Server.dll"]
