# Stage 1: Build the Angular app
FROM node:20 AS build
WORKDIR /app
COPY ./sarah.client/ ./
RUN npm install
RUN npm run build --prod

# Stage 2: Serve the Angular app
FROM nginx:alpine as final
COPY --from=build /app/dist/sarah.client /usr/share/nginx/html
EXPOSE 4200

# Update Nginx configuration to listen on port 4200
RUN sed -i 's/listen       80;/listen       4200;/g' /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]