version: '3.8'

services:
  sarah-server:
    image: localhost:6000/sarah:latest
    ports:
      - "7165:7165"
      - "4200:4200"
    volumes:
    #  - /path/to/your/host/directory:/app/data
      - /var/opt/sarah:/app/data:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CERT_PATH=/app/data/certificate.pfx
      - CERT_PASSWORD=ayayaycaramba
      - HTTPS_BACKEND_PORT=7165
      - HTTPS_FRONTEND_PORT=4200
      - SARAH_DB_PATH=/app/data/InteLuk.db
    

