FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Sarah.SpeechServer/Sarah.SpeechServer.csproj", "Sarah.SpeechServer/"]
COPY ["Services/Sarah.API/Sarah.API.csproj", "Services/Sarah.API/"]
COPY ["Services/Sarah.DeviceServiceClient/Sarah.DeviceServiceClient.csproj", "Services/Sarah.DeviceServiceClient/"]
COPY ["Services/Sarah.EventProcessing/Sarah.EventProcessing.csproj", "Services/Sarah.EventProcessing/"]
COPY ["Services/Sarah.LEDService/Sarah.LEDService.csproj", "Services/Sarah.LEDService/"]
COPY ["Services/Sarah.Voice/Sarah.Voice.csproj", "Services/Sarah.Voice/"]
COPY ["Services/Sarah.Logging/Sarah.Logging.csproj", "Services/Sarah.Logging/"]
RUN dotnet restore "Sarah.SpeechServer/Sarah.SpeechServer.csproj"
COPY . .
WORKDIR "/src/Sarah.SpeechServer"
RUN dotnet build "Sarah.SpeechServer.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Sarah.SpeechServer.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sarah.SpeechServer.dll"]
