<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sarah.API\Sarah.API.csproj" />
    <ProjectReference Include="..\Sarah.Logging\Sarah.Logging.csproj" />
    <ProjectReference Include="..\Sarah.Data\Sarah.Data.csproj" />
    <ProjectReference Include="..\Sarah.Rules\Sarah.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ical.Net" Version="4.3.1" />
  </ItemGroup>

  <!-- Kalender Dateien in output kopieren -->
  <ItemGroup>
    <None Update="assets/ical/**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
