<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="10.0.0" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="10.0.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microservices\Sarah.DeviceService.WebApi\Sarah.DeviceService.WebApi.csproj" />
    <ProjectReference Include="..\Microservices\Sarah.Persons.WebApi\Sarah.Persons.WebApi.csproj" />
    <ProjectReference Include="..\Microservices\Sarah.Geofences.WebApi\Sarah.Geofences.WebApi.csproj" />
    <ProjectReference Include="..\Microservices\Sarah.EventProcessing.WebApi\Sarah.EventProcessing.WebApi.csproj" />
    <ProjectReference Include="..\Microservices\Sarah.Monitoring.WebApi\Sarah.Monitoring.WebApi.csproj" />
    <ProjectReference Include="..\Microservices\Sarah.Rules.WebApi\Sarah.Rules.WebApi.csproj" />
    <ProjectReference Include="..\Microservices\Sarah.API.WebApi\Sarah.API.WebApi.csproj" />
    <ProjectReference Include="..\Sarah.LocationServer\Sarah.LocationServer.csproj" />
    <ProjectReference Include="..\Sarah.SpeechServer\Sarah.SpeechServer.csproj" />
  </ItemGroup>

</Project>
