/**
 * Sarah Admin Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SayRequestModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param sayRequestModel 
     */
    apiAdminSayPost(sayRequestModel?: SayRequestModel, extraHttpRequestParams?: any): Observable<{}>;

}
