export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './devices.service';
import { DevicesService } from './devices.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './persons.service';
import { PersonsService } from './persons.service';
export * from './rooms.service';
import { RoomsService } from './rooms.service';
export * from './status.service';
import { StatusService } from './status.service';
export const APIS = [DashboardService, DevicesService, LocationService, PersonsService, RoomsService, StatusService];
