// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sarah.Statistics.WebApi.Data;

#nullable disable

namespace Sarah.Statistics.WebApi.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    partial class StatisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sarah.Statistics.WebApi.Data.EnergyAggregate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgPowerW")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("EnergyKwh")
                        .HasColumnType("double precision");

                    b.Property<int>("Granularity")
                        .HasColumnType("integer");

                    b.Property<double>("MaxPowerW")
                        .HasColumnType("double precision");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Granularity", "BucketStart");

                    b.HasIndex("DeviceId", "Granularity", "BucketStart")
                        .IsUnique();

                    b.ToTable("EnergyAggregates", (string)null);
                });

            modelBuilder.Entity("Sarah.Statistics.WebApi.Data.EnergySample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("EnergyKwhTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerW")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.HasIndex("Timestamp");

                    b.ToTable("EnergySamples", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
