/**
 * Sarah Device Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BlinkAnimationCommandModel } from '../model/models';
import { StartSceneCommandModel } from '../model/models';
import { StopSceneCommandModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AnimationsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param blinkAnimationCommandModel 
     */
    animationsExecuteBlinkAnimationPOSTApiDevicesAnimationsBlink(blinkAnimationCommandModel?: BlinkAnimationCommandModel, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param startSceneCommandModel 
     */
    animationsStartScenePOSTApiDevicesScenesStart(startSceneCommandModel?: StartSceneCommandModel, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param stopSceneCommandModel 
     */
    animationsStopScenePOSTApiDevicesScenesStop(stopSceneCommandModel?: StopSceneCommandModel, extraHttpRequestParams?: any): Observable<{}>;

}
