/**
 * Sarah Device Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DeviceDtoModel } from '../model/models';
import { SetAssociationGroupRequestModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DevicesClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param deviceDtoModel 
     */
    devicesCreatePUTApiDevices(deviceDtoModel?: DeviceDtoModel, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param deviceDtoModel 
     */
    devicesCreatePUTDevices(deviceDtoModel?: DeviceDtoModel, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesDeleteDELETEApiDevicesId(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesDeleteDELETEDevicesId(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetAllGETApiDevices(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetAllGETDevices(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetAssociationGroupsGETApiDevicesNodesNodeIdAssociationGroups(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetAssociationGroupsGETDevicesNodesNodeIdAssociationGroups(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetBatterySensorsGETApiDevicesBatterysensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetBatterySensorsGETDevicesBatterysensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetControllersGETApiDevicesControllers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetControllersGETDevicesControllers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesGetDeviceByIdGETApiDevicesId(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesGetDeviceByIdGETDevicesId(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetDeviceByNodeIdGETApiDevicesBynodeNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetDeviceByNodeIdGETDevicesBynodeNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetDoorSensorsGETApiDevicesDoorsensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetDoorSensorsGETDevicesDoorsensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetGpsTrackerByNodeIdGETApiDevicesGpstrackerNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetGpsTrackerByNodeIdGETDevicesGpstrackerNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetGpsTrackersGETApiDevicesGpsTrackers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetGpsTrackersGETDevicesGpsTrackers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetLampsGETApiDevicesLamps(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetLampsGETDevicesLamps(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetNetworkElementsGETApiDevicesElements(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetNetworkElementsGETDevicesElements(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetNetworkItemGETApiDevicesNetworkitemNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetNetworkItemGETDevicesNetworkitemNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetNodeGETApiDevicesNodeNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesGetNodeGETDevicesNodeNodeId(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param roomId 
     */
    devicesGetRoomAverageTemperatureGETApiDevicesRoomRoomIdAvgtemperature(roomId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param roomId 
     */
    devicesGetRoomAverageTemperatureGETDevicesRoomRoomIdAvgtemperature(roomId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param roomId 
     */
    devicesGetRoomSummaryGETApiDevicesRoomRoomIdSummary(roomId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param roomId 
     */
    devicesGetRoomSummaryGETDevicesRoomRoomIdSummary(roomId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetSensorsGETApiDevicesSensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetSensorsGETDevicesSensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetSerialPortNameGETApiDevicesSerialPort(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetSerialPortNameGETDevicesSerialPort(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetSmokeSensorsGETApiDevicesSmokesensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetSmokeSensorsGETDevicesSmokesensors(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetStatusGETApiDevicesStatus(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetStatusGETDevicesStatus(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetThermostatsGETApiDevicesThermostats(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetThermostatsGETDevicesThermostats(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetTrackersGETApiDevicesTrackers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetTrackersGETDevicesTrackers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetUnknownElementsGETApiDevicesUnknown(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetUnknownElementsGETDevicesUnknown(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetWallControllersGETApiDevicesWallcontrollers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetWallControllersGETDevicesWallcontrollers(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetWallPlugsGETApiDevicesWallplugs(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    devicesGetWallPlugsGETDevicesWallplugs(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     * @param groupId 
     * @param setAssociationGroupRequestModel 
     */
    devicesSetAssociationGroupPOSTApiDevicesNodesNodeIdAssociationGroupsGroupId(nodeId: number, groupId: number, setAssociationGroupRequestModel?: SetAssociationGroupRequestModel, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     * @param groupId 
     * @param setAssociationGroupRequestModel 
     */
    devicesSetAssociationGroupPOSTDevicesNodesNodeIdAssociationGroupsGroupId(nodeId: number, groupId: number, setAssociationGroupRequestModel?: SetAssociationGroupRequestModel, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param brightness 
     */
    devicesSetLampBrightnessPOSTApiDevicesLampIdBrightnessBrightness(id: number, brightness: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param brightness 
     */
    devicesSetLampBrightnessPOSTDevicesLampIdBrightnessBrightness(id: number, brightness: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesSetLampColdWhiteByNodePOSTApiDevicesBynodeNodeIdLampColdwhite(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesSetLampColdWhiteByNodePOSTDevicesBynodeNodeIdLampColdwhite(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesSetLampColdWhitePOSTApiDevicesLampIdColdwhite(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesSetLampColdWhitePOSTDevicesLampIdColdwhite(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     * @param color 
     * @param brightness 
     */
    devicesSetLampColorAndBrightnessByNodePOSTApiDevicesBynodeNodeIdLampColorColorBrightnessBrightness(nodeId: number, color: string, brightness: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     * @param color 
     * @param brightness 
     */
    devicesSetLampColorAndBrightnessByNodePOSTDevicesBynodeNodeIdLampColorColorBrightnessBrightness(nodeId: number, color: string, brightness: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param color 
     */
    devicesSetLampColorPOSTApiDevicesLampIdColorColor(id: number, color: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param color 
     */
    devicesSetLampColorPOSTDevicesLampIdColorColor(id: number, color: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesSetLampWarmWhiteByNodePOSTApiDevicesBynodeNodeIdLampWarmwhite(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesSetLampWarmWhiteByNodePOSTDevicesBynodeNodeIdLampWarmwhite(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesSetLampWarmWhitePOSTApiDevicesLampIdWarmwhite(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    devicesSetLampWarmWhitePOSTDevicesLampIdWarmwhite(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param temperature 
     */
    devicesSetThermostatTemperaturePOSTApiDevicesThermostatIdTemperatureTemperature(id: number, temperature: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param temperature 
     */
    devicesSetThermostatTemperaturePOSTDevicesThermostatIdTemperatureTemperature(id: number, temperature: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     * @param isOn 
     */
    devicesSetWallPlugStateByNodePOSTApiDevicesBynodeNodeIdWallplugStateIsOn(nodeId: number, isOn: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     * @param isOn 
     */
    devicesSetWallPlugStateByNodePOSTDevicesBynodeNodeIdWallplugStateIsOn(nodeId: number, isOn: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param isOn 
     */
    devicesSetWallplugStateByDeviceIdPOSTApiDevicesWallplugIdStateIsOn(id: number, isOn: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param isOn 
     */
    devicesSetWallplugStateByDeviceIdPOSTDevicesWallplugIdStateIsOn(id: number, isOn: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesToggleLampByNodePOSTApiDevicesBynodeNodeIdLampToggle(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesToggleLampByNodePOSTDevicesBynodeNodeIdLampToggle(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesToggleWallPlugByNodePOSTApiDevicesBynodeNodeIdWallplugToggle(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param nodeId 
     */
    devicesToggleWallPlugByNodePOSTDevicesBynodeNodeIdWallplugToggle(nodeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param deviceDtoModel 
     */
    devicesUpdatePOSTApiDevices(deviceDtoModel?: DeviceDtoModel, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param deviceDtoModel 
     */
    devicesUpdatePOSTDevices(deviceDtoModel?: DeviceDtoModel, extraHttpRequestParams?: any): Observable<{}>;

}
