/**
 * Sarah Persons Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PersonDtoModel } from '../model/models';
import { PersonResponseDtoModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PersonsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiPersonsGet(extraHttpRequestParams?: any): Observable<Array<PersonResponseDtoModel>>;

    /**
     * 
     * 
     * @param id 
     */
    apiPersonsIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     * @param isFavourite 
     */
    apiPersonsIdFavouriteIsFavouritePut(id: number, isFavourite: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiPersonsIdGet(id: number, extraHttpRequestParams?: any): Observable<PersonResponseDtoModel>;

    /**
     * 
     * 
     * @param id 
     * @param personDtoModel 
     */
    apiPersonsIdPut(id: number, personDtoModel?: PersonDtoModel, extraHttpRequestParams?: any): Observable<PersonResponseDtoModel>;

    /**
     * 
     * 
     */
    apiPersonsKnownHomeNetworkDevicesGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param personDtoModel 
     */
    apiPersonsPost(personDtoModel?: PersonDtoModel, extraHttpRequestParams?: any): Observable<PersonResponseDtoModel>;

    /**
     * 
     * 
     */
    apiPersonsStatusGet(extraHttpRequestParams?: any): Observable<{}>;

}
