/**
 * Sarah Admin Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpeechVolumeModel } from './speechVolume';


export interface SayRequestModel { 
    text?: string | null;
    volume?: SpeechVolumeModel;
}



