/**
 * Sarah Monitoring Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface MonitoringClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiMonitoringFerienGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiMonitoringStatusGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiMonitoringWeatherGet(extraHttpRequestParams?: any): Observable<{}>;

}
