// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sarah.Rules.WebApi.Data;

#nullable disable

namespace Sarah.Rules.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sarah.Rules.Data.Entities.AlarmScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AlarmTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasRecurrence")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNichtInFerien")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNurInFerien")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurrence")
                        .HasColumnType("boolean");

                    b.Property<int>("RecurrenceDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("RecurrenceIsEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("RecurrenceTime")
                        .HasColumnType("interval");

                    b.Property<string>("SerializedRecurrence")
                        .HasColumnType("text");

                    b.Property<string>("TargetSpeaker")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlarmSchedules", (string)null);
                });

            modelBuilder.Entity("Sarah.Rules.Data.Entities.TemperatureScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<long?>("Id_Room")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TargetTemperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TemperatureSchedules", (string)null);
                });

            modelBuilder.Entity("Sarah.Rules.WebApi.Data.Entities.RuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Rules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
