<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Services/Sarah.API/Sarah.API.csproj" />
    <ProjectReference Include="../Services/Sarah.DeviceServiceClient/Sarah.DeviceServiceClient.csproj" />
    <ProjectReference Include="../Services/Sarah.EventProcessing/Sarah.EventProcessing.csproj" />
    <ProjectReference Include="../Services/Sarah.LEDService/Sarah.LEDService.csproj" />
    <ProjectReference Include="../Services/Sarah.Voice/Sarah.Voice.csproj" />
  </ItemGroup>

</Project>
