/**
 * Sarah Device Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AirQualityStateDtoModel { 
    cO2?: number | null;
    volatileOrganicCompounds?: number | null;
    relativeHumidity?: number | null;
}

