/**
 * Sarah Device Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WallPlugStateDtoModel } from './wallPlugStateDto';
import { PositionDtoModel } from './positionDto';
import { BatteryStateDtoModel } from './batteryStateDto';
import { ExtendedPropertyDtoModel } from './extendedPropertyDto';
import { DoorSensorStateDtoModel } from './doorSensorStateDto';
import { ThermoStateDtoModel } from './thermoStateDto';
import { AirQualityStateDtoModel } from './airQualityStateDto';
import { LampStateDtoModel } from './lampStateDto';
import { KnownDeviceTypesModel } from './knownDeviceTypes';


export interface DeviceDtoModel { 
    id?: number;
    roomId?: number | null;
    name?: string | null;
    nodeId?: number;
    deviceType?: KnownDeviceTypesModel;
    typeName?: string | null;
    info?: string | null;
    isReadonly?: boolean;
    isFavourite?: boolean;
    position?: PositionDtoModel;
    doorSensor?: DoorSensorStateDtoModel;
    thermostat?: ThermoStateDtoModel;
    airQuality?: AirQualityStateDtoModel;
    battery?: BatteryStateDtoModel;
    lamp?: LampStateDtoModel;
    wallPlug?: WallPlugStateDtoModel;
    extendedProperties?: Array<ExtendedPropertyDtoModel> | null;
}



