/**
 * Sarah Device Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PositionDtoModel } from './positionDto';
import { ExtendedPropertyDtoModel } from './extendedPropertyDto';
import { KnownDeviceTypesModel } from './knownDeviceTypes';


export interface DeviceDtoModel { 
    id?: number;
    roomId?: number | null;
    name?: string | null;
    nodeId?: number;
    deviceType?: KnownDeviceTypesModel;
    typeName?: string | null;
    info?: string | null;
    isReadonly?: boolean;
    isFavourite?: boolean;
    position?: PositionDtoModel;
    extendedProperties?: Array<ExtendedPropertyDtoModel> | null;
}



