/**
 * Sarah Device Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoorSensorStateModel } from './doorSensorState';


export interface DoorSensorStateDtoModel { 
    state?: DoorSensorStateModel;
    lastStateChanged?: string | null;
}



