/**
 * Sarah Device Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LampStateDtoModel { 
    brightness?: number;
    color?: string | null;
    lastChange?: string | null;
}

