/**
 * Sarah Dashboard Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DashboardItemType = 0 | 1 | 2 | 3 | 4;

export const DashboardItemType = {
    NUMBER_0: 0 as DashboardItemType,
    NUMBER_1: 1 as DashboardItemType,
    NUMBER_2: 2 as DashboardItemType,
    NUMBER_3: 3 as DashboardItemType,
    NUMBER_4: 4 as DashboardItemType
};

