/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DashboardItemTypeDto = 0 | 1 | 2 | 3 | 4;

export const DashboardItemTypeDto = {
    NUMBER_0: 0 as DashboardItemTypeDto,
    NUMBER_1: 1 as DashboardItemTypeDto,
    NUMBER_2: 2 as DashboardItemTypeDto,
    NUMBER_3: 3 as DashboardItemTypeDto,
    NUMBER_4: 4 as DashboardItemTypeDto
};

