/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtendedPropertyDto } from './extendedPropertyDto';
import { DashboardItemTypeDto } from './dashboardItemTypeDto';


export interface DashboardItemDto { 
    itemId?: number;
    itemType?: DashboardItemTypeDto;
    title?: string | null;
    description?: string | null;
    subtype?: string | null;
    extendedProperties?: Array<ExtendedPropertyDto> | null;
}
export namespace DashboardItemDto {
}


