/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardItemTypeDto } from './dashboardItemTypeDto';
import { JsonNode } from './jsonNode';


export interface DashboardItemDto { 
    itemId?: number;
    itemType?: DashboardItemTypeDto;
    title?: string | null;
    description?: string | null;
    subtype?: string | null;
    extendedProperties?: { [key: string]: JsonNode; } | null;
}
export namespace DashboardItemDto {
}


