/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KnownDeviceTypes } from './knownDeviceTypes';
import { ExtendedPropertyDto } from './extendedPropertyDto';


export interface DeviceDto { 
    id?: number;
    nodeId?: number;
    typeName?: string | null;
    name?: string | null;
    info?: string | null;
    deviceType?: KnownDeviceTypes;
    roomId?: number | null;
    isReadonly?: boolean;
    isFavourite?: boolean;
    extendedProperties?: Array<ExtendedPropertyDto> | null;
}
export namespace DeviceDto {
}


