/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KnownDeviceTypes } from './knownDeviceTypes';


export interface DeviceDto { 
    readonly id?: number;
    readonly nodeID?: number;
    readonly typeName?: string | null;
    readonly name?: string | null;
    readonly info?: string | null;
    deviceType?: KnownDeviceTypes;
    readonly roomId?: number | null;
}
export namespace DeviceDto {
}


