/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PointDto } from './pointDto';


export interface GeofenceDto { 
    id?: number;
    name?: string | null;
    points?: Array<PointDto> | null;
}

