/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JsonNodeOptions } from './jsonNodeOptions';


export interface JsonNode { 
    options?: JsonNodeOptions;
    parent?: JsonNode;
    root?: JsonNode;
}

