/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type KnownDeviceTypes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19;

export const KnownDeviceTypes = {
    NUMBER_0: 0 as KnownDeviceTypes,
    NUMBER_1: 1 as KnownDeviceTypes,
    NUMBER_2: 2 as KnownDeviceTypes,
    NUMBER_3: 3 as KnownDeviceTypes,
    NUMBER_4: 4 as KnownDeviceTypes,
    NUMBER_5: 5 as KnownDeviceTypes,
    NUMBER_6: 6 as KnownDeviceTypes,
    NUMBER_7: 7 as KnownDeviceTypes,
    NUMBER_8: 8 as KnownDeviceTypes,
    NUMBER_9: 9 as KnownDeviceTypes,
    NUMBER_10: 10 as KnownDeviceTypes,
    NUMBER_11: 11 as KnownDeviceTypes,
    NUMBER_12: 12 as KnownDeviceTypes,
    NUMBER_13: 13 as KnownDeviceTypes,
    NUMBER_14: 14 as KnownDeviceTypes,
    NUMBER_15: 15 as KnownDeviceTypes,
    NUMBER_16: 16 as KnownDeviceTypes,
    NUMBER_17: 17 as KnownDeviceTypes,
    NUMBER_18: 18 as KnownDeviceTypes,
    NUMBER_19: 19 as KnownDeviceTypes
};

