/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NetworkElementDto { 
    readonly id?: number;
    readonly typeName?: string | null;
    readonly name?: string | null;
    readonly info?: string | null;
}

