/**
 * Sarah.Server
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatusDto { 
    hostname?: string | null;
    port?: number;
    isAuthenticated?: boolean;
    username?: string | null;
    controllerStatus?: string | null;
}

