<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sarah.API\Sarah.API.csproj" />
    <ProjectReference Include="..\Sarah.DeviceService\Sarah.DeviceService.csproj" />
  </ItemGroup>

</Project>
