/**
 * Sarah Geofences Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface GeofencesClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param latitude 
     * @param longitude 
     */
    apiGeofencesCurrentGet(latitude?: number, longitude?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiGeofencesGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiGeofencesHomeGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiGeofencesStatusGet(extraHttpRequestParams?: any): Observable<{}>;

}
