/**
 * Sarah Rules Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlarmContentTypeModel } from './alarmContentType';


export interface AlarmContentDtoModel { 
    type?: AlarmContentTypeModel;
    text?: string | null;
    targetSpeaker?: string | null;
    volume?: number | null;
    roomId?: number | null;
    targetTemperature?: number | null;
    dayOfWeek?: number | null;
    suppressDuringSummer?: boolean | null;
}



