/**
 * Sarah Rules Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpeechVolumeModel } from './speechVolume';


export interface AlarmScheduleEntityModel { 
    id?: number;
    alarmTime: string;
    text: string;
    targetSpeaker?: string | null;
    isActive: boolean;
    volume: SpeechVolumeModel;
    isRecurrence?: boolean;
    recurrenceIsEnabled?: boolean;
    recurrenceDayOfWeek?: number;
    recurrenceTime?: string;
    isNurInFerien?: boolean | null;
    isNichtInFerien?: boolean | null;
    isNurInFerienNotNull?: boolean;
    isNichtInFerienNotNull?: boolean;
    hasRecurrence: boolean;
    serializedRecurrence?: string | null;
}



