/**
 * Sarah Rules Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KernelConversationMessageDtoModel { 
    id?: number;
    conversationId?: string | null;
    role?: string | null;
    content?: string | null;
    createdAtUtc?: string;
}

