/**
 * Sarah Rules Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PromptRuleTimerDtoModel { 
    hour?: number;
    minute?: number;
    weekdays?: number;
    interval?: number;
    fromUtc?: string | null;
    untilUtc?: string | null;
}

