/**
 * Sarah Rules Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RuleExecutionLogDtoModel {
    id?: number;
    ruleName: string;
    triggeredAt: string;
    success: boolean;
    errorMessage?: string | null;
}
