/**
 * Sarah Rules Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TemperatureScheduleEntityModel { 
    id?: number;
    id_Room?: number | null;
    startTime?: string;
    targetTemperature?: number;
    dayOfWeek?: number;
}

